### ISSUE TITLE
Cannot find module "ng2-date-countdown"

### ISSUE THREAD

**Issue by ghost** [matheushf/ng2-date-countdown#41]
Hey,

VSCode says it can't find the module after I updated to 1.1.3. 1.1.2 worked fine for me. Angular Version is 8. By the way, does it still work for later versions of angular or do I have to find another module?

**Comment by demiro** [comment]
I have the same issue
